name: EPG Auto Update

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  update-epg:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download EPG
        run: |
          curl -L -o epg-ge.xml http://epg.team/tvteam.3.1.xml

      - name: Commit update
        run: |
          git config --global user.name "epg-bot"
          git config --global user.email "epg-bot@users.noreply.github.com"
          git add epg-ge.xml
          git commit -m "Auto EPG Update"
          git push
